### ISSUE TITLE
Bokeh generator issue

### ISSUE THREAD

**Issue by LegitStack** [vasa-develop/HashPay#4]
Tried running it but there's a problem with the bokeh:

> BokehDeprecationWarning: The ability to remove a callback function using its value was deprecated in Bokeh 0.12.15 and will be removed, use a value returned from the function that adds a callback instead.

coming from 

> File "/home/jmiller/HashPay/hashgraph.py", line 148, in animate
>     new = next(self.main_its[r])

```
/var/anaconda3/lib/python3.6/site-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: The ability to remove a callback function using its value was deprecated in Bokeh 0.12.15 and will be removed, use a value returned from the function that adds a callback instead.
  warn(message)
2018-08-28 10:37:54,208 Error thrown from periodic callback:
2018-08-28 10:37:54,209 Traceback (most recent call last):
  File "/var/anaconda3/lib/python3.6/site-packages/bokeh/server/session.py", line 51, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/var/anaconda3/lib/python3.6/site-packages/bokeh/server/session.py", line 157, in with_document_locked
    return func(*args, **kwargs)
  File "/var/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1076, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/var/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1062, in _with_self_as_curdoc
    return f()
  File "/var/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1075, in invoke
    return f(*args, **kwargs)
  File "/home/jmiller/HashPay/hashgraph.py", line 148, in animate
    new = next(self.main_its[r])
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/var/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/var/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
RuntimeError: generator raised StopIteration

```

**Comment by LegitStack** [comment]
Yes, delete the play and pause symbols in the code
